In [1]:
import tensorflow as tf
from keras.models import load_model
import numpy as np
from PIL import Image
import gradio as gr

# Load the saved model
model = load_model('emergency_classifier.h5')

# Define the prediction function
def predict_image(image):
    # Preprocess the image

    print(image[1])
    
  
    
    image = np.expand_dims(image, axis=0)
    

    # Make predictions
    result = model.predict(image)
    if result[0][0] == 1:
        prediction = 'Non-emergency vehicle'
    else:
        prediction = 'Emergency vehicle'

    return prediction

# Create the interface
iface = gr.Interface(fn=predict_image, 
                      inputs=gr.inputs.Image(label="Upload Image", image_mode='RGB', shape=(64, 64)),
                     outputs=gr.outputs.Textbox(),
                     title="Emergency Vehicle Classifier",
                     description="Upload an image to classify if it's an emergency vehicle or not.")

# Launch the interface
iface.launch()

C:\Users\Madhan\AppData\Roaming\Python\Python39\site-packages\gradio\inputs.py:257: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\Madhan\AppData\Roaming\Python\Python39\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\Madhan\AppData\Roaming\Python\Python39\site-packages\gradio\outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(


Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


[[108 114  30]
 [118 128  46]
 [ 82  79  15]
 [121 110  37]
 [106 106  32]
 [104 105  28]
 [141 138  52]
 [124 127  44]
 [109 125  35]
 [100 107  23]
 [114 120  37]
 [147 152  50]
 [ 93 112  28]
 [111 123  29]
 [134 142  55]
 [128 137  54]
 [114 131  36]
 [ 80  98  18]
 [ 56  69  11]
 [ 74  85  11]
 [ 97 112  22]
 [106 118  25]
 [115 128  32]
 [ 82  93  16]
 [109 117  26]
 [113 121  27]
 [105 117  41]
 [125 141  46]
 [109 119  22]
 [ 89 109  30]
 [ 48  67  20]
 [ 16  18   2]
 [ 68  84  28]
 [ 67  92  27]
 [ 11  21   0]
 [ 12  18   3]
 [ 12  21   2]
 [ 32  50   1]
 [ 35  56   7]
 [ 43  60   9]
 [ 25  31   2]
 [ 24  19   1]
 [ 29  40   2]
 [ 15  29   4]
 [ 26  34   9]
 [  4   8   2]
 [ 10  19   2]
 [ 10  22   2]
 [ 21  33   4]
 [ 42  55   6]
 [ 20  20   4]
 [ 17  18   4]
 [ 15  26   2]
 [ 61  80  14]
 [ 39  62  12]
 [ 31  47   1]
 [ 40  54   1]
 [ 65  79  16]
 [ 88 102  24]
 [ 79  98  18]
 [ 51  65  10]
 [ 25  36   5]
 [  6  13   2]
 [ 10  24   2]]
1/1 [==============================] - 

In [4]:
model